import type { Metadata } from "next";
import { Cinzel_Decorative, Geist, Geist_Mono, Raleway } from "next/font/google";
import "./globals.css";


 const raleway= Raleway({
  variable:'--font-raleway',
  subsets:['latin'],
  weight:['100','200','300','400','500','600','700','800']

 })

 const cinzel= Cinzel_Decorative({
 variable:'--font-cinzel',
 subsets:['latin'],
 weight:['400','700','900']

})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable} ${cinzel.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
